Coleta-Colchao/Controllers/GerenciamentoController.cs
using Coleta_Colchao.Data;
using Coleta_Colchao.Models;
using Coleta_Colchao.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;



namespace Coleta_Colchao.Controllers
{
    [Authorize]
    public class GerenciamentoController : Controller
    {
        private readonly ILogger<GerenciamentoController> _logger;
        private readonly ColchaoContext _context;
        private readonly BancoContext _bancoContext;

        public GerenciamentoController(ILogger<GerenciamentoController> logger, ColchaoContext colchaoContex, BancoContext bancoContext)
        {
            _logger = logger;
            _context = colchaoContex;
            _bancoContext = bancoContext;
        }

        public IActionResult Molas()
        {

            var dados = (from molas in _context.regtro_colchao
                         where molas.andamento == "Andamento" || molas.andamento == "Finalizado"
                         select new Models.Gerenciamento
                         {
                             Id = molas.Id,
                             os = molas.os,
                             orcamento = molas.orcamento,
                             andamento = molas.andamento
                         }).ToList();

            return View(dados);
        }


        public IActionResult Espuma()
        {
            var dados = (from espuma in _context.regtro_colchao_espuma
                         where espuma.andamento == "Andamento" || espuma.andamento == "Finalizado"
                         select new Gerenciamento
                         {
                             Id = espuma.Id,
                             os = espuma.os,
                             orcamento = espuma.orcamento,
                             andamento = espuma.andamento
                         }).ToList();

            return View(dados);
        }
        public IActionResult Laminas()
        {
            var dados = (from espuma in _context.regtro_colchao_lamina
                         where espuma.andamento == "Andamento" || espuma.andamento == "Finalizado"
                         select new Gerenciamento
                         {
                             Id = espuma.Id,
                             os = espuma.os,
                             orcamento = espuma.orcamento,
                             andamento = espuma.andamento
                         }).ToList();

            return View(dados);
        }

        public async Task<IActionResult> buscarGerenciamentoMolas(string ensaio)
        {
            try
            {
                if (ensaio == "Não iniciado")
                {
                    //quando coleta nao esta iniciado
                    var subQuery = (from colchao_os in _context.regtro_colchao
                                    where colchao_os.andamento != "Andamento" && colchao_os.andamento != "Finalizado"
                                    select colchao_os.os
                                    ).ToList();

                    var dados = (from lab_os in _bancoContext.ordemservico_laboratorio
                                 where lab_os.Laboratorio == "Colchão" && !subQuery.Contains(lab_os.OS) && lab_os.DataSaidaAmReceb > new DateOnly(2024, 4, 10)
                                 select new Gerenciamento
                                 {
                                     os = lab_os.OS,
                                     orcamento = lab_os.orcamento,
                                     andamento = "Não Iniciado",
                                 }).ToList();

                    return View("Molas", dados);

                }
                else if (ensaio == "Andamento")
                {
                    //quando coleta esta andamento
                    var dados = (from molas in _context.regtro_colchao
                                 where molas.andamento == "Andamento"
                                 select new Gerenciamento
                                 {
                                     Id = molas.Id,
                                     os = molas.os,
                                     orcamento = molas.orcamento,
                                     andamento = molas.andamento,
                                 }).ToList();
                    return View("Molas", dados);
                }
                else
                {
                    //quando esta finalizada.
                    var dados = (from molas in _context.regtro_colchao
                                 where molas.andamento == "Finalizado"
                                 select new Gerenciamento
                                 {
                                     Id = molas.Id,
                                     os = molas.os,
                                     orcamento = molas.orcamento,
                                     andamento = molas.andamento,
                                 }).ToList();

                    return View("Molas", dados);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error", ex.Message);
                throw;
            }
        }

        public async Task<IActionResult> buscarGerenciamentoEspuma(string ensaio)
        {
            try
            {
                if (ensaio == "Não iniciado")
                {
                    var subQuery = (from colchao_os in _context.regtro_colchao_espuma
                                    where colchao_os.andamento != "Andamento" && colchao_os.andamento != "Finalizado"
                                    select colchao_os.os
                                   ).ToList();

                    var dados = (from lab_os in _bancoContext.ordemservico_laboratorio
                                 where lab_os.Laboratorio == "Colchão" && !subQuery.Contains(lab_os.OS) && lab_os.DataSaidaAmReceb > new DateOnly(2024, 4, 10)
                                 select new Gerenciamento
                                 {
                                     os = lab_os.OS,
                                     orcamento = lab_os.orcamento,
                                     andamento = "Não Iniciado",
                                 }).ToList();

                    return View("Espuma", dados);
                }
                else if (ensaio == "Andamento")
                {
                    var dados = (from espuma in _context.regtro_colchao_espuma
                                 where espuma.andamento == "Andamento"
                                 select new Gerenciamento
                                 {
                                     Id = espuma.Id,
                                     os = espuma.os,
                                     orcamento = espuma.orcamento,
                                     andamento = espuma.andamento,
                                 }).ToList();

                    return View("Espuma", dados);
                }
                else
                {
                    var dados = (from espuma in _context.regtro_colchao_espuma
                                 where espuma.andamento == "Finalizado"
                                 select new Gerenciamento
                                 {
                                     Id = espuma.Id,
                                     os = espuma.os,
                                     orcamento = espuma.orcamento,
                                     andamento = espuma.andamento,
                                 }).ToList();

                    return View("Espuma", dados);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error", ex.Message);
                throw;
            }
        }

        public async Task<IActionResult> buscarGerenciamentoLaminas(string ensaio)
        {
            try
            {
                if (ensaio == "Não iniciado")
                {
                    var subQuery = (from colchao_os in _context.regtro_colchao_lamina
                                    where colchao_os.andamento != "Andamento" && colchao_os.andamento != "Finalizado"
                                    select colchao_os.os
                                   ).ToList();

                    var dados = (from lab_os in _bancoContext.ordemservico_laboratorio
                                 where lab_os.Laboratorio == "Colchão" && !subQuery.Contains(lab_os.OS) && lab_os.DataSaidaAmReceb > new DateOnly(2024, 4, 10)
                                 select new Gerenciamento
                                 {
                                     os = lab_os.OS,
                                     orcamento = lab_os.orcamento,
                                     andamento = "Não Iniciado",
                                 }).ToList();

                    return View("Laminas", dados);
                }
                else if (ensaio == "Andamento")
                {
                    var dados = (from espuma in _context.regtro_colchao_lamina
                                 where espuma.andamento == "Andamento"
                                 select new Gerenciamento
                                 {
                                     Id = espuma.Id,
                                     os = espuma.os,
                                     orcamento = espuma.orcamento,
                                     andamento = espuma.andamento,
                                 }).ToList();

                    return View("Laminas", dados);
                }
                else
                {
                    var dados = (from espuma in _context.regtro_colchao_lamina
                                 where espuma.andamento == "Finalizado"
                                 select new Gerenciamento
                                 {
                                     Id = espuma.Id,

Coleta-Colchao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Coleta Colcão</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Coleta_Colchao.styles.css" asp-append-version="true" />
    <style>
        a:hover{
            font-color: #000;
            background-color: lightseagreen;
            cursor:pointer;
            border-radius:5px;
        }

        .ml-auto {
            margin-left: auto;
        }
        #id-footer {
            display: flex;
            justify-content: center;
            align-content: center;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ex2">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gerenciamento" asp-action="Molas">Gerenciamento de molas</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gerenciamento" asp-action="Espuma">Gerenciamento de espuma</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gerenciamento" asp-action="Laminas">Gerenciamento de laminas</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="LogOut">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>