Coleta-Colchao/Controllers/ColetaController.cs
using Coleta_Colchao.Data;
using Coleta_Colchao.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.VisualBasic;
using NuGet.Versioning;
using System.Data.Entity;
using System.Data.Entity.Core.Mapping;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Reflection.Metadata.Ecma335;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Security.Policy;
using static Coleta_Colchao.Models.ColetaModel;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Coleta_Colchao.Controllers
{
    [Authorize]
    //[Route("Coleta")]
    public class ColetaController : Controller
    {
        //conexao..
        private readonly ILogger<ColetaController> _logger;
        private readonly ColchaoContext _context;
        private readonly BancoContext _bancoContext;

        public ColetaController(ILogger<ColetaController> logger, ColchaoContext colchaoContex, BancoContext bancoContext)
        {
            _logger = logger;
            _context = colchaoContex;
            _bancoContext = bancoContext;
        }

        public IActionResult Index(string os, string orcamento)
        {
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            return View();
        }

        // função para saber qual usuario esta logado para salvar ou editar.
        public string Usuario()
        {
            var user = User.FindFirstValue(ClaimTypes.Name);
            var nomeCompleto = _bancoContext.usuario.Where(x => x.Nome_Usuario == user).FirstOrDefault();

            return nomeCompleto.nomecompleto;
        }


        public IActionResult IndexMolas(string os, string orcamento)
        {
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            return View("Molas/IndexMolas");
        }
        public IActionResult IndexLamina(string os, string orcamento)
        {
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            return View("Laminas/IndexLamina");
        }
        public IActionResult EditarLamina(string os, string orcamento, int rev)
        {
            var dados = _context.regtro_colchao_lamina.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            ViewBag.rev = rev;
            return View("Laminas/EditarLamina", dados);
        }
        public IActionResult IndexEspuma(string os, string orcamento)
        {
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            return View("Espuma/IndexEspuma");
        }

        public IActionResult EditarIndexEspuma(string os, string orcamento, int rev)
        {
            var dados = _context.regtro_colchao_espuma.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();
            ViewBag.os = os;
            ViewBag.orcamento = orcamento;
            ViewBag.rev = rev;
            return View("Espuma/EditarIndexEspuma", dados);
        }

        public IActionResult EditarRegistroMolas(string os, string orcamento, int rev)
        {
            var dados = _context.regtro_colchao.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).ToList();
            if (dados != null)
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                return View("Molas/EditarRegistroMolas", dados);
            }
            else
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                return View();
            }
        }
        private List<SelectListItem> buscarResponsaveisPelaConferencia (string responsavel)
        {
            string valorSalvo = responsavel;

            // Criamos a lista de opções
            var listaParaDropdown = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = ResponsaveisPelaConferencia.Encarregado,
                    Text = ResponsaveisPelaConferencia.Encarregado,
                    // Definimos 'Selected' se o valor for igual ao salvo no banco
                    Selected = ResponsaveisPelaConferencia.Encarregado == valorSalvo
                },
                new SelectListItem
                {
                    Value = ResponsaveisPelaConferencia.Chefe,
                    Text = ResponsaveisPelaConferencia.Chefe,
                    Selected = ResponsaveisPelaConferencia.Chefe == valorSalvo
                }
            };

            // Não adicione o "Selecione..." se um valor já estiver selecionado, para evitar confusão.
            if (string.IsNullOrEmpty(valorSalvo))
            {
                listaParaDropdown.Insert(0, new SelectListItem { Value = "", Text = "Selecione um responsável..." });
            }

            return listaParaDropdown;
        }

        public IActionResult Condicionamento(string os, string orcamento, int rev)
        {
            var dados = _context.condicionamento
                        .Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev)
                        .FirstOrDefault();

            var registroMolas = _context.regtro_colchao.Where(x => x.os == os && x.orcamento == orcamento).FirstOrDefault();
            var registroLaminas = _context.regtro_colchao_lamina.Where(x => x.os == os && x.orcamento == orcamento).FirstOrDefault();
            var registroEspuma = _context.regtro_colchao_espuma.Where(x => x.os == os && x.orcamento == orcamento).FirstOrDefault();

            ViewBag.listaResponsaveis = buscarResponsaveisPelaConferencia(dados?.editorUsuario);

            if (dados != null)
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;

                if(registroMolas != null && registroMolas.Bloqueada == "Sim")
                {
                    ViewBag.Bloqueada = registroMolas.Bloqueada;
                }

                if (registroLaminas != null && registroLaminas.Bloqueada == "Sim")
                {
                    ViewBag.Bloqueada = registroLaminas.Bloqueada;
                }

                if (registroEspuma != null && registroEspuma.Bloqueada == "Sim")
                {
                    ViewBag.Bloqueada = registroEspuma.Bloqueada;
                }
                return View(dados);
            }
            else
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;

                return View();
            }
        }

        public IActionResult EnsaioEspuma4_1(string os, string orcamento, int rev)
        {
            var dados = _context.ensaio_espuma4_1.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();

            ViewBag.listaResponsaveis = buscarResponsaveisPelaConferencia(dados?.editarUsuario);
            var RegistroEspuma = _context.regtro_colchao_espuma.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();
            //verificando largura,altura e comprimento do index.
            ViewBag.comprimento = RegistroEspuma.comprimento;
            ViewBag.largura = RegistroEspuma.largura;
            ViewBag.altura = RegistroEspuma.altura;

            if (dados != null)
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                ViewBag.quantidadeLaminas = RegistroEspuma.quant_laminas;
                ViewBag.tipoColchao = RegistroEspuma.tipo_colchao;
                ViewBag.revestimento = RegistroEspuma.revestimento;
                ViewBag.bloqueada = RegistroEspuma.Bloqueada;
                return View("Espuma/EnsaioEspuma4_1", dados);
            }
            else
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                ViewBag.quantidadeLaminas = RegistroEspuma.quant_laminas;
                ViewBag.tipoColchao = RegistroEspuma.tipo_colchao;
                ViewBag.revestimento = RegistroEspuma.revestimento;
                return View("Espuma/EnsaioEspuma4_1");
            }
        }

        public IActionResult Espuma4_4(string os, string orcamento, int rev)
        {
            var inicial = _context.regtro_colchao_espuma.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();
            var dados = _context.ensaio_espuma_item_4_4.Where(x => x.os == os && x.orcamento == orcamento && x.rev == rev).FirstOrDefault();

            ViewBag.listaResponsaveis = buscarResponsaveisPelaConferencia(dados?.editarUsuario);

            if (dados == null)
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                return View("Espuma/Espuma4_4");

            }
            else
            {
                ViewBag.os = os;
                ViewBag.orcamento = orcamento;
                ViewBag.rev = rev;
                ViewBag.bloqueada = inicial.Bloqueada;
                return View("Espuma/Espuma4_4", dados);
            }
        }

Coleta-Colchao/Views/Coleta/Laminas/EditarLamina.cshtml
@model ColetaModel.RegistroLamina;
@{
    ViewData["Title"] = "Index Lamina";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/coleta.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .full-height {
            min-height: 80vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            border-bottom: 2px solid rgba(255,255,255, 0.1);
            align-items: center;
        }

        .hidden {
            opacity: 0;
            filter: blur(15px);
            transform: translateX(-100%);
            transition: all 0.2s;
        }

        .show {
            opacity: 1;
            filter: blur(0);
            transform: translateX(0);
            transition: all 0.5s;
        }

        .sessaodois {
            display: none;
        }

        .estilo-select {
            background-color: #F0F0F0;
            border: 1px solid #CCCCCC;
            padding: 5px;
            border-radius: 5px;
        }

        .densidade_1, .densidade_2, .densidade_3, .densidade_4, .densidade_5 {
            display: none;
        }

        body {
            padding: 0px;
            margin: 0;
            background-color: #fafafa;
        }
    </style>
</head>
<body>
    <form method="post" asp-controller="Coleta" asp-action="editarLamina" asp-route-os="@ViewBag.os" asp-route-orcamento="@ViewBag.orcamento" asp-route-rev="@ViewBag.rev">
        <div class="full-height text-center">
            <table class="tables table-bordered border-secondary  table-sm">
                <tr>
                    <td colspan="5" class="fundo-tabela">
                        <h1>
                            Informações Iniciais
                        </h1>
                    </td>
                </tr>
                <tr>
                    <td> Orçamento : </td>
                    <td colspan="4"> <input class="form-control" type="text" value="@ViewBag.orcamento" readonly name="orcamento" /> </td>
                </tr>
                <tr>
                    <td> Ordem de serviço : </td>
                    <td colspan="4"> <input class="form-control" type="text" value="@ViewBag.os" readonly name="os" /> </td>
                </tr>
                <tr>
                    <td> Contém Lacre : </td>
                    <td>
                        <select class="form-control" asp-for="lacre">
                            <option value="Sim">Sim</option>
                            <option value="Não">Não</option>
                        </select>
                    </td>
                    <td> Local da realização dos ensaios : </td>
                    <td colspan="2"> <input class="form-control" type="text" asp-for="realizacao_ensaios" value="Labsystem" readonly /> </td>
                </tr>
                <tr>
                    <td> Quantidade recebida : </td>
                    <td> <input class="form-control" type="text" asp-for="quant_recebida" /> </td>
                    <td> Quantidade Ensaiada :  </td>
                    <td colspan="2"> <input class="form-control" type="text" asp-for="quant_ensaiada" /> </td>
                </tr>
                <tr>
                    <td> Data de realização dos ensaios: </td>
                    <td> Ínicio: </td>
                    <td> <input class="form-control" type="text" asp-for="data_realizacao_ini" /> </td>
                    <td> Término :  </td>
                    <td> <input class="form-control" type="text" asp-for="data_realizacao_term" /> </td>
                </tr>
            </table>

            <table class="tables table-bordered border-secondary  table-sm">
                <tr>
                    <td>Produto</td>
                    <td colspan="5"><input class="form-control" type="text" asp-for="produto" /></td>
                </tr>
                <tr>
                    <td>Marca / Modelo</td>
                    <td colspan="5"><input class="form-control" type="text" asp-for="marca_modelo" /></td>
                </tr>
                <tr>
                    <td>Portaria</td>
                    <td colspan="5">
                        <select class="form-control" asp-for="portaria">
                            <option value="35">35</option>
                            <option value="75">75</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td> Número de processo </td>
                    <td> <input class="form-control" type="text" asp-for="num_proc" /> </td>
                    <td> Código de referência </td>
                    <td> <input class="form-control" type="text" asp-for="cod_ref" /> </td>
                    <td> Descrição </td>
                    <td> <input class="form-control" type="text" asp-for="desc_lamina" /> </td>
                </tr>
                <tr>
                    <td> Tipo de certificação </td>
                    <td colspan="3"> Modelo de certificação </td>
                    <td colspan="3"> Tipo de processo: </td>
                </tr>
                <tr>
                    <td> <input class="form-control" type="text" asp-for="tipo_cert" /> </td>
                    <td colspan="3"> <input class="form-control" type="text" asp-for="modelo_cert" /> </td>
                    <td colspan="3"> <input class="form-control" type="text" asp-for="tipo_proc" /> </td>
                </tr>
            </table>

            @if (Model.Bloqueada != "Sim")
            {
                <div class="d-grid gap-2 d-flex justify-content-center">
                    <button type="submit" class="btn btn-success"> Salvar Informações</button>
                </div>

            }
            else
            {
                <div class="alert alert-danger w-50 p-3 m-3" role="alert">
                    Coleta Bloqueada!
                </div>
            }
        </div>
    </form>
    <br /><br />
    <footer class="d-flex justify-content-center align-items-center border-top bg-white py-3 fixed-bottom" style="margin: auto; width: 100%; bottom: 0; position: fixed;">
        <div class="d-flex align-items-center">
            <a asp-controller="Home" asp-action="Index" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img src="https://www.labsystem-nuvem.com.br/imagens_arq/imagens/img/LabSystem.png" class="bi" width="25" height="24" />
            </a>
            <span class="mb-4 mb-md-0 text-body-secondary" style="font-size: 14px;">&copy; Coleta Colchao - CD-SI 001/MVS - 10/02/2025 - Rev 1</span>
        </div>
    </footer>
    @if (TempData.ContainsKey("Mensagem"))
    {
        <script>
            alert('@Html.Raw(TempData["Mensagem"])');
        </script>
    }
</body>
</html>

Coleta-Colchao/Views/Coleta/Laminas/IndexLamina.cshtml
@model ColetaModel.RegistroLamina;
@{
    ViewData["Title"] = "Index Lamina";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/coleta.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .full-height {
            min-height: 80vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            border-bottom: 2px solid rgba(255,255,255, 0.1);
            align-items: center;
        }

        .hidden {
            opacity: 0;
            filter: blur(15px);
            transform: translateX(-100%);
            transition: all 0.2s;
        }

        .show {
            opacity: 1;
            filter: blur(0);
            transform: translateX(0);
            transition: all 0.5s;
        }

        .sessaodois {
            display: none;
        }

        .estilo-select {
            background-color: #F0F0F0;
            border: 1px solid #CCCCCC;
            padding: 5px;
            border-radius: 5px;
        }

        .densidade_1, .densidade_2, .densidade_3, .densidade_4, .densidade_5 {
            display: none;
        }

        body {
            padding: 0px;
            margin: 0;
            background-color: #fafafa;
        }
    </style>
</head>
<body>


    <form method="post" asp-controller="Coleta" asp-action="salvarLamina" asp-route-os="@ViewBag.os" asp-route-orcamento="@ViewBag.orcamento">
        <div class="full-height text-center">
            <table class="tables table-bordered border-secondary  table-sm">
                <tr>
                    <td colspan="5" class="fundo-tabela">
                        <h1>
                            Informações Iniciais
                        </h1>
                    </td>
                </tr>
                <tr>
                    <td> Orçamento : </td>
                    <td colspan="4"> <input class="form-control" type="text" value="@ViewBag.orcamento" readonly name="orcamento" /> </td>
                </tr>
                <tr>
                    <td> Ordem de serviço : </td>
                    <td colspan="4"> <input class="form-control" type="text" value="@ViewBag.os" readonly name="os" /> </td>
                </tr>
                <tr>
                    <td> Contém Lacre : </td>
                    <td>
                        <select class="form-control" asp-for="lacre">
                            <option value="Sim">Sim</option>
                            <option value="Não">Não</option>
                        </select>
                    </td>
                    <td> Local da realização dos ensaios : </td>
                    <td colspan="2"> <input class="form-control" type="text" asp-for="realizacao_ensaios" value="Labsystem" readonly /> </td>
                </tr>
                <tr>
                    <td> Quantidade recebida : </td>
                    <td> <input class="form-control" type="text" asp-for="quant_recebida" /> </td>
                    <td> Quantidade Ensaiada :  </td>
                    <td colspan="2"> <input class="form-control" type="text" asp-for="quant_ensaiada" /> </td>
                </tr>
                <tr>
                    <td> Data de realização dos ensaios: </td>
                    <td> Ínicio: </td>
                    <td> <input class="form-control" type="date" asp-for="data_realizacao_ini" /> </td>
                    <td> Término :  </td>
                    <td> <input class="form-control" type="date" asp-for="data_realizacao_term" /> </td>
                </tr>
            </table>

            <table class="tables table-bordered border-secondary  table-sm">
                <tr>
                    <td>Produto</td>
                    <td colspan="5"><input class="form-control" type="text" asp-for="produto" /></td>
                </tr>
                <tr>
                    <td>Marca / Modelo</td>
                    <td colspan="5"><input class="form-control" type="text" asp-for="marca_modelo" /></td>
                </tr>
                <tr>
                    <td>Portaria</td>
                    <td colspan="5">
                        <select class="form-control" asp-for="portaria">
                            <option value="35">35</option>
                            <option value="75">75</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td> Número de processo </td>
                    <td> <input class="form-control" type="text" asp-for="num_proc" /> </td>
                    <td> Código de referência </td>
                    <td> <input class="form-control" type="text" asp-for="cod_ref" /> </td>
                    <td> Descrição </td>
                    <td> <input class="form-control" type="text" asp-for="desc_lamina" /> </td>
                </tr>
                <tr>
                    <td> Tipo de certificação </td>
                    <td colspan="3"> Modelo de certificação </td>
                    <td colspan="3"> Tipo de processo: </td>
                </tr>
                <tr>
                    <td> <input class="form-control" type="text" asp-for="tipo_cert" /> </td>
                    <td colspan="3"> <input class="form-control" type="text" asp-for="modelo_cert" /> </td>
                    <td colspan="3"> <input class="form-control" type="text" asp-for="tipo_proc" /> </td>
                </tr>
            </table>
            <tr>
                <td>
                    <button type="submit" class="btn btn-success"> Salvar Informações</button>
                </td>
            </tr>
        </div>
    </form>
   
    <footer class="d-flex justify-content-center align-items-center border-top bg-white py-3 fixed-bottom" style="margin: auto; width: 100%; bottom: 0; position: fixed;">
        <div class="d-flex align-items-center">
            <a asp-controller="Home" asp-action="Index" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <img src="https://www.labsystem-nuvem.com.br/imagens_arq/imagens/img/LabSystem.png" class="bi" width="25" height="24" />
            </a>
            <span class="mb-4 mb-md-0 text-body-secondary" style="font-size: 14px;">&copy; Coleta Colchao - CD-SI 001/MVS - 10/02/2025 - Rev 1</span>
        </div>
    </footer>
    @if (TempData.ContainsKey("Mensagem"))
    {
        <script>
            alert('@Html.Raw(TempData["Mensagem"])');
        </script>
    }
</body>
</html>